config/routes.rb
Rails.application.routes.draw do
  mount Dashing::Engine, at: Dashing.config.engine_path
  root 'main#index'

  scope module: 'freelancer' do
    get 'freelancer' => 'freelancer#index'
    post 'freelancer/contact_me' => 'freelancer#contact_me'
  end

  scope module: 'maps' do
    resources :maps
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :markers, only: [:index]
    end
  end
end

app/models/freelancer.rb
class Freelancer < ActiveRecord::Base
  validates :name, presence:  { message: 'Заполните поле.' }
  validates :email, presence:  { message: 'Заполните поле.' },
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/,
                      message: 'Неверный формат.'}
end

app/models/map.rb
class Map < ActiveRecord::Base
  has_many :markers, dependent: :destroy
  accepts_nested_attributes_for :markers,  reject_if: :all_blank, allow_destroy: true

  validates :title, presence: { message: 'Заполните поле.' }
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  belongs_to :map

  validates :title, presence: { message: 'Заполните поле.' }
  validates :latitude, :longitude,
            format: { with: /\A-?\d{1,10}\.\d{1,6}\z/i,
                      message: 'Неверный формат.'},
            presence: { message: 'Заполните поле.' }
end

app/controllers/api/v1/api_controller.rb
class API::V1::ApiController < ActionController::API
end

app/controllers/api/v1/markers_controller.rb
module Api
  module V1
    class MarkersController < API::V1::ApiController
      respond_to :json

      def index
        @markers = Marker.last(5)
        render :index
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/freelancer/base_controller.rb
class Freelancer::BaseController < ApplicationController
end

app/controllers/freelancer/freelancer_controller.rb
class Freelancer::FreelancerController < Freelancer::BaseController
  respond_to :html
  layout 'freelancer'

  def index
    @freelancer = Freelancer.new
  end

  def contact_me
    @freelancer = Freelancer.new(freelancer_params)
    FreelancerMailer.contact_me(freelancer_params[:email]).deliver_now if @freelancer.save

    redirect_to freelancer_path
  end

  private

  def freelancer_params
    params.require(:freelancer).permit(:name, :email, :phone, :message)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  respond_to :html

  def index
  end
end

app/controllers/maps/base_controller.rb
class Maps::BaseController < ApplicationController
end

app/controllers/maps/maps_controller.rb
class Maps::MapsController < Freelancer::BaseController
  before_action :set_map, only: [:destroy, :edit, :update, :show]

  respond_to :html, :js

  def index
    @maps = Map.all
  end

  def show
    @markers = build_markers
  end

  def new
    @map = Map.new
    @map.markers.build
  end

  def edit
    @markers = build_markers
  end

  def create
    @map = Map.new(map_params)
    if @map.save
      @markers = build_markers

      redirect_to edit_map_path(@map)
    else
      respond_with @map
    end
  end

  def update
    if @map.update(map_params)
      @markers = build_markers

      respond_to do |format|
        format.html { redirect_to edit_map_path(@map) }
        format.js
      end
    else
      respond_with @map
    end
  end

  def destroy
    @map.destroy
    respond_with @map
  end

  private

  def set_map
    @map = Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:title,
                                markers_attributes: [:id, :title, :comment,
                                                     :latitude, :longitude,
                                                     :_destroy])
  end

  def build_markers
    @map_markers = @map.markers.all

    @markers = Gmaps4rails.build_markers(@map_markers) do |map_marker, marker|
      marker.lat map_marker.latitude
      marker.lng map_marker.longitude
      marker.title map_marker.title
      marker.infowindow map_marker.comment
      marker.picture({
                       url: 'https://maps.gstatic.com/mapfiles/ms2/micons/red-dot.png',
                       width:  36,
                       height: 36
                     })
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashing/dashboards/sample.html.erb
<% content_for :title do %>
  My super sweet dashboard
<% end %>

<div class="gridster">
  <ul>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="2">
      <div data-id="buzzwords" data-view="List" data-unordered="true" data-title="Buzzwords" data-moreinfo="# of times said around the office"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="valuation" data-view="Number" data-title="Current Valuation" data-moreinfo="In billions" data-prefix="$"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="convergence" data-view="Graph" data-title="Convergence" style="background-color:#ff9618"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="3" data-sizey="1">
      <div data-id="markers" data-view="Markers"></div>
    </li>
  </ul>
</div>

app/views/freelancer/freelancer/_about.html.erb
<section class="success" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>About</h2>
        <hr class="star-light">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-lg-offset-2">
        <p>Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>
      </div>
      <div class="col-lg-4">
        <p>Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>
      </div>
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <a href="#" class="btn btn-lg btn-outline">
          <i class="fa fa-download"></i> Download Theme
        </a>
      </div>
    </div>
  </div>
</section>

app/views/freelancer/freelancer/_contact.html.erb
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Contact Me</h2>
        <hr class="star-primary">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">

        <%= render 'freelancer/freelancer/contact_me_form' %>

      </div>
    </div>
  </div>
</section>

app/views/freelancer/freelancer/_contact_me_form.html.erb
<%= form_tag '/freelancer/contact_me', method: 'post' do %>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <label>Name</label>
      <input type="text" class="form-control" placeholder="Name" id="name"
             required data-validation-required-message="Please enter your name."
             name="freelancer[name]">
      <p class="help-block text-danger"></p>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <label>Email Address</label>
      <input type="email" class="form-control" placeholder="Email Address" id="email"
             required data-validation-required-message="Please enter your email address."
             name="freelancer[email]">
      <p class="help-block text-danger"></p>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <label>Mobile Phone</label>
      <input type="tel" class="form-control" placeholder="Mobile Phone" id="phone"
             name="freelancer[phone]">
      <p class="help-block text-danger"></p>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <label>Message</label>
      <textarea rows="5" class="form-control" placeholder="Message" id="message"
                name="freelancer[message]"></textarea>
      <p class="help-block text-danger"></p>
    </div>
  </div>
  <br>
  <div id="success"></div>
  <div class="row">
    <div class="form-group col-xs-12">
      <button type="submit" class="btn btn-success btn-lg">Send</button>
    </div>
  </div>
<% end %>

app/views/freelancer/freelancer/_footer.html.erb
<footer class="text-center">
  <div class="footer-above">
    <div class="container">
      <div class="row">
        <div class="footer-col col-md-4">
          <h3>Location</h3>
          <p>3481 Melrose Place<br>Beverly Hills, CA 90210</p>
        </div>
        <div class="footer-col col-md-4">
          <h3>Around the Web</h3>
          <ul class="list-inline">
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
            </li>
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
            </li>
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
            </li>
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
            </li>
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
            </li>
          </ul>
        </div>
        <div class="footer-col col-md-4">
          <h3>About Freelancer</h3>
          <p>Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-below">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          Copyright &copy; Your Website 2014
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/freelancer/freelancer/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <img class="img-responsive" src="freelancer/profile.png" alt="">
        <div class="intro-text">
          <span class="name">Start Bootstrap</span>
          <hr class="star-light">
          <span class="skills">Web Developer - Graphic Artist - User Experience Designer</span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/freelancer/freelancer/_portfolio_grid.html.erb
<section id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Portfolio</h2>
        <hr class="star-primary">
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-search-plus fa-3x"></i>
            </div>
          </div>
          <img src="freelancer/portfolio/cabin.png" class="img-responsive" alt="">
        </a>
      </div>
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-search-plus fa-3x"></i>
            </div>
          </div>
          <img src="freelancer/portfolio/cake.png" class="img-responsive" alt="">
        </a>
      </div>
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-search-plus fa-3x"></i>
            </div>
          </div>
          <img src="freelancer/portfolio/circus.png" class="img-responsive" alt="">
        </a>
      </div>
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-search-plus fa-3x"></i>
            </div>
          </div>
          <img src="freelancer/portfolio/game.png" class="img-responsive" alt="">
        </a>
      </div>
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-search-plus fa-3x"></i>
            </div>
          </div>
          <img src="freelancer/portfolio/safe.png" class="img-responsive" alt="">
        </a>
      </div>
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-search-plus fa-3x"></i>
            </div>
          </div>
          <img src="freelancer/portfolio/submarine.png" class="img-responsive" alt="">
        </a>
      </div>
    </div>
  </div>
</section>

app/views/freelancer/freelancer/_portfolio_modal.html.erb
<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">
            <h2>Project Title</h2>
            <hr class="star-primary">
            <img src="freelancer/portfolio/cabin.png" class="img-responsive img-centered" alt="">
            <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
            <ul class="list-inline item-details">
              <li>Client:
                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                </strong>
              </li>
              <li>Date:
                <strong><a href="http://startbootstrap.com">April 2014</a>
                </strong>
              </li>
              <li>Service:
                <strong><a href="http://startbootstrap.com">Web Development</a>
                </strong>
              </li>
            </ul>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">
            <h2>Project Title</h2>
            <hr class="star-primary">
            <img src="freelancer/portfolio/cake.png" class="img-responsive img-centered" alt="">
            <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
            <ul class="list-inline item-details">
              <li>Client:
                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                </strong>
              </li>
              <li>Date:
                <strong><a href="http://startbootstrap.com">April 2014</a>
                </strong>
              </li>
              <li>Service:
                <strong><a href="http://startbootstrap.com">Web Development</a>
                </strong>
              </li>
            </ul>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">
            <h2>Project Title</h2>
            <hr class="star-primary">
            <img src="freelancer/portfolio/circus.png" class="img-responsive img-centered" alt="">
            <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
            <ul class="list-inline item-details">
              <li>Client:
                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                </strong>
              </li>
              <li>Date:
                <strong><a href="http://startbootstrap.com">April 2014</a>
                </strong>
              </li>
              <li>Service:
                <strong><a href="http://startbootstrap.com">Web Development</a>
                </strong>
              </li>
            </ul>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">
            <h2>Project Title</h2>
            <hr class="star-primary">
            <img src="freelancer/portfolio/game.png" class="img-responsive img-centered" alt="">
            <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
            <ul class="list-inline item-details">
              <li>Client:
                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                </strong>
              </li>
              <li>Date:
                <strong><a href="http://startbootstrap.com">April 2014</a>
                </strong>
              </li>
              <li>Service:
                <strong><a href="http://startbootstrap.com">Web Development</a>
                </strong>
              </li>
            </ul>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">
            <h2>Project Title</h2>
            <hr class="star-primary">
            <img src="freelancer/portfolio/safe.png" class="img-responsive img-centered" alt="">
            <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
            <ul class="list-inline item-details">
              <li>Client:
                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                </strong>
              </li>
              <li>Date:
                <strong><a href="http://startbootstrap.com">April 2014</a>
                </strong>
              </li>
              <li>Service:
                <strong><a href="http://startbootstrap.com">Web Development</a>
                </strong>
              </li>
            </ul>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">
            <h2>Project Title</h2>
            <hr class="star-primary">
            <img src="freelancer/portfolio/submarine.png" class="img-responsive img-centered" alt="">
            <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
            <ul class="list-inline item-details">
              <li>Client:
                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                </strong>
              </li>
              <li>Date:
                <strong><a href="http://startbootstrap.com">April 2014</a>
                </strong>
              </li>
              <li>Service:
                <strong><a href="http://startbootstrap.com">Web Development</a>
                </strong>
              </li>
            </ul>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/freelancer/freelancer/index.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li class="page-scroll">
          <a href="#portfolio">Portfolio</a>
        </li>
        <li class="page-scroll">
          <a href="#about">About</a>
        </li>
        <li class="page-scroll">
          <a href="#contact">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<%= render 'freelancer/freelancer/header' %>
<%= render 'freelancer/freelancer/portfolio_grid' %>
<%= render 'freelancer/freelancer/about' %>
<%= render 'freelancer/freelancer/contact' %>
<%= render 'freelancer/freelancer/footer' %>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll visible-xs visible-sm">
  <a class="btn btn-primary" href="#page-top">
    <i class="fa fa-chevron-up"></i>
  </a>
</div>

<%= render 'freelancer/freelancer/portfolio_modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMPublisher</title>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="container" id="wrapper">
  <%= render 'shared/header' %>
  <div class="row" id="middle">
    <div id="notice_block">
      <%= render 'shared/alert_notice' %>
    </div>
    <div class="col-sm-12">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/maps/maps/_form.html.erb
<%= simple_form_for map do |f| %>
  <div class="form-group">
    <%= f.input :title, label: 'Название карты',
                input_html: { class: 'form-control', autofocus: true } %>
  </div>

  <% if params[:action] == 'edit' %>
    <div class="form-group">
      <%= label_tag 'Адрес карты: ', nil %>
      <%= map_url %>
    </div>
  <% end %>

  <%= render 'maps/markers/all_markers', map: map %>

  <div class="form-group" id="add_marker_fields">
    <%= link_to_add_association 'Добавить метку', f, :markers,
                                class: 'btn btn-default', role: 'button',
                                partial: 'maps/markers/marker_fields'%>
    <%= f.button :submit, 'Сохранить карту', class: 'btn btn-default' %>
    <%= link_to 'Вернуться назад', maps_path, class: 'btn btn-default',
                role: 'button', data: { confirm: 'Продолжить без сохранения изменений?' } %>
  </div>

  <%= hidden_field_tag :latitude %>
  <%= hidden_field_tag :longitude %>
<% end %>

<div id="add_edit_map">
  <%= render 'map' %>
</div>

<script>
  $(function() {
    $("#add_marker_fields a.add_fields").
        data("association-insertion-method", 'append').
        data("association-insertion-node", '#markers');

    $("#edit_map_<%= @map.id %>").attr('data-remote', 'true')
  });
</script>

app/views/maps/maps/index.html.erb
<h2>Мои карты</h2>

<% if @maps.any? %>
  <table class="table">
    <thead>
    <tr>
      <th>Карта</th>
      <th>Адрес</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @maps.each do |map| %>
      <tr class="table">
        <td><%= map.title %></td>
        <td><%= map_url(map) %></td>
        <td class="col-md-1"><%= link_to 'Показать', map_path(map) %></td>
        <td class="col-md-1"><%= link_to 'Редактировать', edit_map_path(map) %></td>
        <td class="col-md-1"><%= link_to 'Удалить', map, method: :delete,
                    data: { confirm: 'Удалить карту?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Добавить карту', new_map_path, class: 'btn btn-default', role: 'button' %>

app/views/maps/maps/show.html.erb
<h2>Просмотр карты</h2>

<div class="form-group">
  <%= label_tag 'Название карты: ', nil %>
  <%= @map.title %>
</div>

<div class="form-group">
  <%= label_tag 'Адрес карты: ', nil %>
  <%= map_url %>
</div>

<%= render 'map' %>

app/views/shared/_header.html.erb
<div class="row" id="header">
  <div class="col-sm-12">
    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                  data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'IMPublisher', root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Задание № 1', maps_path %></li>
            <li><%= link_to 'Задание № 2', freelancer_path, target: '_blank' %></li>
            <li><%= link_to 'Задание № 3', dashing_path, target: '_blank' %></li>
          </ul>
        </div>

      </div>
    </nav>
  </div>
</div>